# Generated by Django 3.0.7 on 2020-06-24 21:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField(null=True)),
            ],
            options={
                'db_table': 'system"."app',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.TextField(default='', null=True)),
                ('number', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'system"."document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'system"."documentline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('salt', models.TextField()),
                ('email', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False, null=True)),
                ('enabled', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'system"."user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'system"."user_app',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classtype', models.TextField(db_index=True)),
                ('prefix', models.TextField(null=True)),
                ('number', models.IntegerField()),
                ('name', models.TextField(null=True)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'storage"."catalog',
                'managed': True,
            },
        ),
    ]
