# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2020-04-17 20:37
from __future__ import unicode_literals

import datetime
from pony import orm

dependencies = []

def define_entities(db):
    class TestTable(db.Entity):
        Column1 = orm.Optional(str)
        Column2 = orm.Optional(str)
        Column3 = orm.Optional(int)
        Column4 = orm.Optional(float)
        Column5 = orm.Optional(datetime.datetime)
