# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2020-05-15 12:14
from __future__ import unicode_literals

from pony import orm
from pony.migrate import diagram_ops as op

dependencies = ['0002_2020-05-13_19-32-21']

operations = [
    op.ModifyAttr('User', 'email', orm.Optional(str, unique=True))]
